### ISSUE TITLE
Maturity, contributing. 

### ISSUE THREAD

**Issue by stephenjlewis** [spacecowboy/orgparser#1]
Hey, just wondering how mature this project is: I see you haven't labelled any releases, but after committing regularly in a few bursts throughout last year, you've tapered off in development. 

If you're still looking to implement a few things, I could give you a hand. 

Thanks!

**Comment by spacecowboy** [comment]
Hi. It is mature in the sense that my Android notes app (only client I know of) uses it quite successfully to sync with SD card files:
https://github.com/spacecowboy/NotePad

The features which are implemented so far supports everything the app does, so I have had no particular reason to go further. I had considered making a specific OrgMode android app (one that looks good...)  but I have not had the free time for such a project.

While I welcome contributions, the amount of people that would benefit from time spent on this particular project might be limited at the moment :/

**Comment by stephenjlewis** [comment]
Incidentally, I found this project while specifically searching for resources that would be useful in creating just such an org-mode app. 

I also have a pretty full plate at the moment, but once I have a little more free time, given the wide range of free-software note apps on github and Google Play, it shouldn't be too hard to put something together which provides a superior org-mode experience than is possible with current offerings. 

For interest's sake, how much time on a regular basis do you spend maintaining your NotePad app?

**Comment by spacecowboy** [comment]
Lately, let's say about 8-16 hours per month. I consider it pretty much feature complete. Only a few serious bugs I'd like squashed.

The selection of Note apps on the store is indeed quite extensive. Personally, I am moving much of my focus towards F-Droid instead, which only hosts open source applications. And in that case, the selection is not even close to the play store.

Do you have much experience with Android?
