### ISSUE TITLE
Incomplete switch in OrgTimestamp::toString

### ISSUE THREAD

**Issue by smelc** [spacecowboy/orgparser#7]
Hello there and thanks for the good job.

I use your plugin to check completeness of data against specifications written in .org files, so far so good! I've got one little remark though. In OrgTimestamp, in method `toString(Locale)`, there's an incomplete switch, since the enum member "PLAIN" is unmatched. Is this intended ? If yes, could you add an empty "case PLAIN" statement (like this: http://pastebin.com/ZYQvBUXJ), so that the switch becomes complete, and Eclipse's compiler doesn't issue a warning at this position ?

**Comment by spacecowboy** [comment]
I would suppose that it's intended, but sure I can add that.

**Comment by smelc** [comment]
:+1:
